# Load Multiple Excel Sheets

## The quickest way ðŸš€

In [1]:
from pathlib import Path

import pandas as pd

# Define filepath
current_dir = Path(__file__).parent if "__file__" in locals() else Path.cwd()
excel_filepath = current_dir / "data.xlsx"

# Set sheet_name to 'None'
df_dict = pd.read_excel(excel_filepath, sheet_name=None)
df_dict

{'Germany':               Segment  Country    Product Discount Band  Units Sold  \
 0          Government  Germany  Carretera          None      1321.0
 1           Midmarket  Germany  Carretera          None       888.0
 2          Government  Germany  Carretera          None      1513.0
 3           Midmarket  Germany    Montana          None       921.0
 4    Channel Partners  Germany    Montana          None      1545.0
 ..                ...      ...        ...           ...         ...
 135        Enterprise  Germany      Paseo          High      1085.0
 136         Midmarket  Germany      Paseo          High      1175.0
 137         Midmarket  Germany        VTT          High       492.0
 138         Midmarket  Germany        VTT          High      1175.0
 139        Enterprise  Germany        VTT          High       552.0

      Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  \
 0                      3          20      26420.0       0.00   26420.00
 1                      3          15      13320.0       0.00   13320.00
 2                      3         350     529550.0       0.00  529550.00
 3                      5          15      13815.0       0.00   13815.00
 4                      5          12      18540.0       0.00   18540.00
 ..                   ...         ...          ...        ...        ...
 135                   10         125     135625.0   20343.75  115281.25
 136                   10          15      17625.0    2643.75   14981.25
 137                  250          15       7380.0    1107.00    6273.00
 138                  250          15      17625.0    2643.75   14981.25
 139                  250         125      69000.0   10350.00   58650.00

        COGS     Profit  Month Number Month Name  Year
 0     13210   13210.00             1    January  2014
 1      8880    4440.00             6       June  2014
 2    393380  136170.00            12   December  2014
 3      9210    4605.00             3      March  2014
 4      4635   13905.00             6       June  2014
 ..      ...        ...           ...        ...   ...
 135  130200  -14918.75            10    October  2014
 136   11750    3231.25            10    October  2014
 137    4920    1353.00             7       July  2014
 138   11750    3231.25            10    October  2014
 139   66240   -7590.00            11   November  2014

 [140 rows x 15 columns],
 'Canada':               Segment Country    Product Discount Band  Units Sold  \
 0          Government  Canada  Carretera          None      1618.5
 1    Channel Partners  Canada    Montana          None      2518.0
 2          Enterprise  Canada    Montana          None      2665.5
 3          Enterprise  Canada    Montana          None       345.0
 4          Government  Canada      Paseo          None       292.0
 ..                ...     ...        ...           ...         ...
 135         Midmarket  Canada      Paseo          High      1614.0
 136         Midmarket  Canada      Paseo          High      2559.0
 137        Government  Canada        VTT          High       865.5
 138        Enterprise  Canada        VTT          High      2954.0
 139        Government  Canada      Paseo          High       723.0

      Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  \
 0                      3          20      32370.0       0.00   32370.00
 1                      5          12      30216.0       0.00   30216.00
 2                      5         125     333187.5       0.00  333187.50
 3                      5         125      43125.0       0.00   43125.00
 4                     10          20       5840.0       0.00    5840.00
 ..                   ...         ...          ...        ...        ...
 135                   10          15      24210.0    3631.50   20578.50
 136                   10          15      38385.0    5757.75   32627.25
 137                  250          20      17310.0    2596.50   14713.50
 138                  250         125     369250.0   55387.50  313862.50
 139                   10           7       5061.0     759.15    4301.85

          COGS    Profit  Month Number Month Name  Year
 0     16185.0  16185.00             1    January  2014
 1      7554.0  22662.00             6       June  2014
 2    319860.0  13327.50             7       July  2014
 3     41400.0   1725.00            10    October  2013
 4      2920.0   2920.00             2   February  2014
 ..        ...       ...           ...        ...   ...
 135   16140.0   4438.50             4      April  2014
 136   25590.0   7037.25             8     August  2014
 137    8655.0   6058.50             7       July  2014
 138  354480.0 -40617.50            11   November  2013
 139    3615.0    686.85             4      April  2014

 [140 rows x 15 columns],
 'United States Of America':               Segment                   Country   Product Discount Band  \
 0           Midmarket  United States Of America   Montana          None
 1          Government  United States Of America     Paseo          None
 2    Channel Partners  United States Of America     Paseo          None
 3          Enterprise  United States Of America      Velo          None
 4    Channel Partners  United States Of America  Amarilla          None
 ..                ...                       ...       ...           ...
 135    Small Business  United States Of America      Velo          High
 136        Enterprise  United States Of America      Velo          High
 137  Channel Partners  United States Of America      Velo          High
 138        Government  United States Of America       VTT          High
 139  Channel Partners  United States Of America       VTT          High

      Units Sold  Manufacturing Price  Sale Price  Gross Sales  Discounts  \
 0         615.0                    5          15       9225.0        0.0
 1        1143.0                   10           7       8001.0        0.0
 2         912.0                   10          12      10944.0        0.0
 3        2821.0                  120         125     352625.0        0.0
 4        1953.0                  260          12      23436.0        0.0
 ..          ...                  ...         ...          ...        ...
 135      2574.0                  120         300     772200.0   115830.0
 136      2438.0                  120         125     304750.0    45712.5
 137       914.0                  120          12      10968.0     1645.2
 138       267.0                  250          20       5340.0      801.0
 139      1806.0                  250          12      21672.0     3250.8

         Sales      COGS   Profit  Month Number Month Name  Year
 0      9225.0    6150.0   3075.0            12   December  2014
 1      8001.0    5715.0   2286.0            10    October  2014
 2     10944.0    2736.0   8208.0            11   November  2013
 3    352625.0  338520.0  14105.0             8     August  2014
 4     23436.0    5859.0  17577.0             4      April  2014
 ..        ...       ...      ...           ...        ...   ...
 135  656370.0  643500.0  12870.0            11   November  2013
 136  259037.5  292560.0 -33522.5            12   December  2013
 137    9322.8    2742.0   6580.8            12   December  2014
 138    4539.0    2670.0   1869.0            10    October  2013
 139   18421.2    5418.0  13003.2             5        May  2014

 [140 rows x 15 columns],
 'Mexico':               Segment Country    Product Discount Band  Units Sold  \
 0           Midmarket  Mexico  Carretera          None        2470
 1           Midmarket  Mexico    Montana          None        2470
 2      Small Business  Mexico    Montana          None         958
 3           Midmarket  Mexico      Paseo          None         974
 4          Government  Mexico      Paseo          None         883
 ..                ...     ...        ...           ...         ...
 135        Government  Mexico      Paseo          High        2851
 136        Government  Mexico      Paseo          High        2151
 137  Channel Partners  Mexico       Velo          High         500
 138    Small Business  Mexico   Amarilla          High         546
 139        Government  Mexico    Montana          High        1368

      Manufacturing Price  Sale Price  Gross Sales  Discounts     Sales  \
 0                      3          15        37050        0.0   37050.0
 1                      5          15        37050        0.0   37050.0
 2                      5         300       287400        0.0  287400.0
 3                     10          15        14610        0.0   14610.0
 4                     10           7         6181        0.0    6181.0
 ..                   ...         ...          ...        ...       ...
 135                   10         350       997850   149677.5  848172.5
 136                   10         350       752850   112927.5  639922.5
 137                  120          12         6000      900.0    5100.0
 138                  260         300       163800    24570.0  139230.0
 139                    5           7         9576     1436.4    8139.6

        COGS    Profit  Month Number Month Name  Year
 0     24700   12350.0             6       June  2014
 1     24700   12350.0             6       June  2014
 2    239500   47900.0             8     August  2014
 3      9740    4870.0             2   February  2014
 4      4415    1766.0             8     August  2014
 ..      ...       ...           ...        ...   ...
 135  741260  106912.5             5        May  2014
 136  559260   80662.5            11   November  2013
 137    1500    3600.0             3      March  2014
 138  136500    2730.0            10    October  2014
 139    6840    1299.6             2   February  2014

 [140 rows x 15 columns],
 'France':             Segment Country    Product Discount Band  Units Sold  \
 0         Midmarket  France  Carretera          None      2178.0
 1        Government  France    Montana          None      1899.0
 2         Midmarket  France      Paseo          None       549.0
 3        Enterprise  France       Velo          None      1804.0
 4         Midmarket  France        VTT          None      2178.0
 ..              ...     ...        ...           ...         ...
 135      Government  France      Paseo          High       293.0
 136       Midmarket  France       Velo          High      2826.0
 137      Enterprise  France       Velo          High       663.0
 138      Government  France        VTT          High       293.0
 139  Small Business  France   Amarilla          High      2475.0

      Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  \
 0                      3          15      32670.0       0.00   32670.00
 1                      5          20      37980.0       0.00   37980.00
 2                     10          15       8235.0       0.00    8235.00
 3                    120         125     225500.0       0.00  225500.00
 4                    250          15      32670.0       0.00   32670.00
 ..                   ...         ...          ...        ...        ...
 135                   10          20       5860.0     879.00    4981.00
 136                  120          15      42390.0    6358.50   36031.50
 137                  120         125      82875.0   12431.25   70443.75
 138                  250          20       5860.0     879.00    4981.00
 139                  260         300     742500.0  111375.00  631125.00

          COGS    Profit  Month Number Month Name  Year
 0     21780.0  10890.00             6       June  2014
 1     18990.0  18990.00             6       June  2014
 2      5490.0   2745.00             9  September  2013
 3    216480.0   9020.00             2   February  2014
 4     21780.0  10890.00             6       June  2014
 ..        ...       ...           ...        ...   ...
 135    2930.0   2051.00            12   December  2014
 136   28260.0   7771.50             5        May  2014
 137   79560.0  -9116.25             9  September  2014
 138    2930.0   2051.00            12   December  2014
 139  618750.0  12375.00             3      March  2014

 [140 rows x 15 columns],
 'India':      Unnamed: 0      Unnamed: 1 Unnamed: 2 Unnamed: 3     Unnamed: 4  \
 0           NaN         Segment    Country    Product  Discount Band
 1           NaN       Midmarket     France  Carretera           None
 2           NaN      Government     France    Montana           None
 3           NaN       Midmarket     France      Paseo           None
 4           NaN      Enterprise     France       Velo           None
 ..          ...             ...        ...        ...            ...
 136         NaN      Government     France      Paseo           High
 137         NaN       Midmarket     France       Velo           High
 138         NaN      Enterprise     France       Velo           High
 139         NaN      Government     France        VTT           High
 140         NaN  Small Business     France   Amarilla           High

      Unnamed: 5           Unnamed: 6  Unnamed: 7   Unnamed: 8 Unnamed: 9  \
 0    Units Sold  Manufacturing Price  Sale Price  Gross Sales  Discounts
 1          2178                    3          15        32670          0
 2          1899                    5          20        37980          0
 3           549                   10          15         8235          0
 4          1804                  120         125       225500          0
 ..          ...                  ...         ...          ...        ...
 136         293                   10          20         5860        879
 137        2826                  120          15        42390     6358.5
 138         663                  120         125        82875   12431.25
 139         293                  250          20         5860        879
 140        2475                  260         300       742500     111375

     Unnamed: 10 Unnamed: 11 Unnamed: 12   Unnamed: 13 Unnamed: 14 Unnamed: 15
 0         Sales        COGS      Profit  Month Number  Month Name        Year
 1         32670       21780       10890             6        June        2014
 2         37980       18990       18990             6        June        2014
 3          8235        5490        2745             9   September        2013
 4        225500      216480        9020             2    February        2014
 ..          ...         ...         ...           ...         ...         ...
 136        4981        2930        2051            12    December        2014
 137     36031.5       28260      7771.5             5         May        2014
 138    70443.75       79560    -9116.25             9   September        2014
 139        4981        2930        2051            12    December        2014
 140      631125      618750       12375             3       March        2014

 [141 rows x 16 columns]}

In [2]:
# Check all sheet names
df_dict.keys()

dict_keys(['Germany', 'Canada', 'United States Of America', 'Mexico', 'France', 'India'])

In [3]:
# Access sheets by their name
df_dict.get("Germany")

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Month Name,Year
0,Government,Germany,Carretera,None,1321.0,3,20,26420.0,0.00,26420.00,13210,13210.00,1,January,2014
1,Midmarket,Germany,Carretera,None,888.0,3,15,13320.0,0.00,13320.00,8880,4440.00,6,June,2014
2,Government,Germany,Carretera,None,1513.0,3,350,529550.0,0.00,529550.00,393380,136170.00,12,December,2014
3,Midmarket,Germany,Montana,None,921.0,5,15,13815.0,0.00,13815.00,9210,4605.00,3,March,2014
4,Channel Partners,Germany,Montana,None,1545.0,5,12,18540.0,0.00,18540.00,4635,13905.00,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,Enterprise,Germany,Paseo,High,1085.0,10,125,135625.0,20343.75,115281.25,130200,-14918.75,10,October,2014
136,Midmarket,Germany,Paseo,High,1175.0,10,15,17625.0,2643.75,14981.25,11750,3231.25,10,October,2014
137,Midmarket,Germany,VTT,High,492.0,250,15,7380.0,1107.00,6273.00,4920,1353.00,7,July,2014
138,Midmarket,Germany,VTT,High,1175.0,250,15,17625.0,2643.75,14981.25,11750,3231.25,10,October,2014
139,Enterprise,Germany,VTT,High,552.0,250,125,69000.0,10350.00,58650.00,66240,-7590.00,11,November,2014

In [4]:
# ...but there will be an issue, if the data in each sheet is located in a different position
df_dict.get("India")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Month Name,Year
1,NaN,Midmarket,France,Carretera,None,2178,3,15,32670,0,32670,21780,10890,6,June,2014
2,NaN,Government,France,Montana,None,1899,5,20,37980,0,37980,18990,18990,6,June,2014
3,NaN,Midmarket,France,Paseo,None,549,10,15,8235,0,8235,5490,2745,9,September,2013
4,NaN,Enterprise,France,Velo,None,1804,120,125,225500,0,225500,216480,9020,2,February,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,NaN,Government,France,Paseo,High,293,10,20,5860,879,4981,2930,2051,12,December,2014
137,NaN,Midmarket,France,Velo,High,2826,120,15,42390,6358.5,36031.5,28260,7771.5,5,May,2014
138,NaN,Enterprise,France,Velo,High,663,120,125,82875,12431.25,70443.75,79560,-9116.25,9,September,2014
139,NaN,Government,France,VTT,High,293,250,20,5860,879,4981,2930,2051,12,December,2014
140,NaN,Small Business,France,Amarilla,High,2475,260,300,742500,111375,631125,618750,12375,3,March,2014

## The flexible way ðŸ’¡

In [5]:
from pathlib import Path
import pandas as pd

# Define filepath
current_dir = Path(__file__).parent if "__file__" in locals() else Path.cwd()
excel_filepath = current_dir / "data.xlsx"

# Load the Excel file
xl_file = pd.ExcelFile(excel_filepath)

# Now you can list all sheets in the file
xl_file.sheet_names

['Germany', 'Canada', 'United States Of America', 'Mexico', 'France', 'India']

**Use additional arguments:** <br/>
*https://pandas.pydata.org/docs/reference/api/pandas.ExcelFile.parse.html* <br/>
ExcelFile.parse(sheet_name=0, 
                header=0, 
                names=None, 
                index_col=None, 
                usecols=None, 
                queeze=None, 
                converters=None, 
                true_values=None, 
                false_values=None, 
                skiprows=None, 
                nrows=None, 
                na_values=None, 
                parse_dates=False, 
                date_parser=None, 
                thousands=None, 
                comment=None, 
                skipfooter=0, 
                convert_float=None, 
                mangle_dupe_cols=True)

In [6]:
# Create dicts for the arguments
usecols = {
    "Germany": "A,C,E:F",
    "France": "B:B",
    "India": "B:P",
}

skiprows = {
    "India": 1
}

# Use additional arguments to read the sheets
df_dict_flex = {}
for sheet_name in xl_file.sheet_names:
    df_dict_flex[sheet_name] = xl_file.parse(sheet_name, 
                                             usecols=usecols.get(sheet_name, None),
                                             skiprows=skiprows.get(sheet_name, None),
                                            )
df_dict_flex

{'Germany':               Segment    Product  Units Sold  Manufacturing Price
 0          Government  Carretera      1321.0                    3
 1           Midmarket  Carretera       888.0                    3
 2          Government  Carretera      1513.0                    3
 3           Midmarket    Montana       921.0                    5
 4    Channel Partners    Montana      1545.0                    5
 ..                ...        ...         ...                  ...
 135        Enterprise      Paseo      1085.0                   10
 136         Midmarket      Paseo      1175.0                   10
 137         Midmarket        VTT       492.0                  250
 138         Midmarket        VTT      1175.0                  250
 139        Enterprise        VTT       552.0                  250

 [140 rows x 4 columns],
 'Canada':               Segment Country    Product Discount Band  Units Sold  \
 0          Government  Canada  Carretera          None      1618.5
 1    Channel Partners  Canada    Montana          None      2518.0
 2          Enterprise  Canada    Montana          None      2665.5
 3          Enterprise  Canada    Montana          None       345.0
 4          Government  Canada      Paseo          None       292.0
 ..                ...     ...        ...           ...         ...
 135         Midmarket  Canada      Paseo          High      1614.0
 136         Midmarket  Canada      Paseo          High      2559.0
 137        Government  Canada        VTT          High       865.5
 138        Enterprise  Canada        VTT          High      2954.0
 139        Government  Canada      Paseo          High       723.0

      Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  \
 0                      3          20      32370.0       0.00   32370.00
 1                      5          12      30216.0       0.00   30216.00
 2                      5         125     333187.5       0.00  333187.50
 3                      5         125      43125.0       0.00   43125.00
 4                     10          20       5840.0       0.00    5840.00
 ..                   ...         ...          ...        ...        ...
 135                   10          15      24210.0    3631.50   20578.50
 136                   10          15      38385.0    5757.75   32627.25
 137                  250          20      17310.0    2596.50   14713.50
 138                  250         125     369250.0   55387.50  313862.50
 139                   10           7       5061.0     759.15    4301.85

          COGS    Profit  Month Number Month Name  Year
 0     16185.0  16185.00             1    January  2014
 1      7554.0  22662.00             6       June  2014
 2    319860.0  13327.50             7       July  2014
 3     41400.0   1725.00            10    October  2013
 4      2920.0   2920.00             2   February  2014
 ..        ...       ...           ...        ...   ...
 135   16140.0   4438.50             4      April  2014
 136   25590.0   7037.25             8     August  2014
 137    8655.0   6058.50             7       July  2014
 138  354480.0 -40617.50            11   November  2013
 139    3615.0    686.85             4      April  2014

 [140 rows x 15 columns],
 'United States Of America':               Segment                   Country   Product Discount Band  \
 0           Midmarket  United States Of America   Montana          None
 1          Government  United States Of America     Paseo          None
 2    Channel Partners  United States Of America     Paseo          None
 3          Enterprise  United States Of America      Velo          None
 4    Channel Partners  United States Of America  Amarilla          None
 ..                ...                       ...       ...           ...
 135    Small Business  United States Of America      Velo          High
 136        Enterprise  United States Of America      Velo          High
 137  Channel Partners  United States Of America      Velo          High
 138        Government  United States Of America       VTT          High
 139  Channel Partners  United States Of America       VTT          High

      Units Sold  Manufacturing Price  Sale Price  Gross Sales  Discounts  \
 0         615.0                    5          15       9225.0        0.0
 1        1143.0                   10           7       8001.0        0.0
 2         912.0                   10          12      10944.0        0.0
 3        2821.0                  120         125     352625.0        0.0
 4        1953.0                  260          12      23436.0        0.0
 ..          ...                  ...         ...          ...        ...
 135      2574.0                  120         300     772200.0   115830.0
 136      2438.0                  120         125     304750.0    45712.5
 137       914.0                  120          12      10968.0     1645.2
 138       267.0                  250          20       5340.0      801.0
 139      1806.0                  250          12      21672.0     3250.8

         Sales      COGS   Profit  Month Number Month Name  Year
 0      9225.0    6150.0   3075.0            12   December  2014
 1      8001.0    5715.0   2286.0            10    October  2014
 2     10944.0    2736.0   8208.0            11   November  2013
 3    352625.0  338520.0  14105.0             8     August  2014
 4     23436.0    5859.0  17577.0             4      April  2014
 ..        ...       ...      ...           ...        ...   ...
 135  656370.0  643500.0  12870.0            11   November  2013
 136  259037.5  292560.0 -33522.5            12   December  2013
 137    9322.8    2742.0   6580.8            12   December  2014
 138    4539.0    2670.0   1869.0            10    October  2013
 139   18421.2    5418.0  13003.2             5        May  2014

 [140 rows x 15 columns],
 'Mexico':               Segment Country    Product Discount Band  Units Sold  \
 0           Midmarket  Mexico  Carretera          None        2470
 1           Midmarket  Mexico    Montana          None        2470
 2      Small Business  Mexico    Montana          None         958
 3           Midmarket  Mexico      Paseo          None         974
 4          Government  Mexico      Paseo          None         883
 ..                ...     ...        ...           ...         ...
 135        Government  Mexico      Paseo          High        2851
 136        Government  Mexico      Paseo          High        2151
 137  Channel Partners  Mexico       Velo          High         500
 138    Small Business  Mexico   Amarilla          High         546
 139        Government  Mexico    Montana          High        1368

      Manufacturing Price  Sale Price  Gross Sales  Discounts     Sales  \
 0                      3          15        37050        0.0   37050.0
 1                      5          15        37050        0.0   37050.0
 2                      5         300       287400        0.0  287400.0
 3                     10          15        14610        0.0   14610.0
 4                     10           7         6181        0.0    6181.0
 ..                   ...         ...          ...        ...       ...
 135                   10         350       997850   149677.5  848172.5
 136                   10         350       752850   112927.5  639922.5
 137                  120          12         6000      900.0    5100.0
 138                  260         300       163800    24570.0  139230.0
 139                    5           7         9576     1436.4    8139.6

        COGS    Profit  Month Number Month Name  Year
 0     24700   12350.0             6       June  2014
 1     24700   12350.0             6       June  2014
 2    239500   47900.0             8     August  2014
 3      9740    4870.0             2   February  2014
 4      4415    1766.0             8     August  2014
 ..      ...       ...           ...        ...   ...
 135  741260  106912.5             5        May  2014
 136  559260   80662.5            11   November  2013
 137    1500    3600.0             3      March  2014
 138  136500    2730.0            10    October  2014
 139    6840    1299.6             2   February  2014

 [140 rows x 15 columns],
 'France':     Country
 0    France
 1    France
 2    France
 3    France
 4    France
 ..      ...
 135  France
 136  France
 137  France
 138  France
 139  France

 [140 rows x 1 columns],
 'India':             Segment Country    Product Discount Band  Units Sold  \
 0         Midmarket  France  Carretera          None      2178.0
 1        Government  France    Montana          None      1899.0
 2         Midmarket  France      Paseo          None       549.0
 3        Enterprise  France       Velo          None      1804.0
 4         Midmarket  France        VTT          None      2178.0
 ..              ...     ...        ...           ...         ...
 135      Government  France      Paseo          High       293.0
 136       Midmarket  France       Velo          High      2826.0
 137      Enterprise  France       Velo          High       663.0
 138      Government  France        VTT          High       293.0
 139  Small Business  France   Amarilla          High      2475.0

      Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  \
 0                      3          15      32670.0       0.00   32670.00
 1                      5          20      37980.0       0.00   37980.00
 2                     10          15       8235.0       0.00    8235.00
 3                    120         125     225500.0       0.00  225500.00
 4                    250          15      32670.0       0.00   32670.00
 ..                   ...         ...          ...        ...        ...
 135                   10          20       5860.0     879.00    4981.00
 136                  120          15      42390.0    6358.50   36031.50
 137                  120         125      82875.0   12431.25   70443.75
 138                  250          20       5860.0     879.00    4981.00
 139                  260         300     742500.0  111375.00  631125.00

          COGS    Profit  Month Number Month Name  Year
 0     21780.0  10890.00             6       June  2014
 1     18990.0  18990.00             6       June  2014
 2      5490.0   2745.00             9  September  2013
 3    216480.0   9020.00             2   February  2014
 4     21780.0  10890.00             6       June  2014
 ..        ...       ...           ...        ...   ...
 135    2930.0   2051.00            12   December  2014
 136   28260.0   7771.50             5        May  2014
 137   79560.0  -9116.25             9  September  2014
 138    2930.0   2051.00            12   December  2014
 139  618750.0  12375.00             3      March  2014

 [140 rows x 15 columns]}

In [7]:
df_dict_flex.get("Germany").head()

            Segment    Product  Units Sold  Manufacturing Price
0        Government  Carretera      1321.0                    3
1         Midmarket  Carretera       888.0                    3
2        Government  Carretera      1513.0                    3
3         Midmarket    Montana       921.0                    5
4  Channel Partners    Montana      1545.0                    5

In [8]:
df_dict_flex.get("India").head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Month Name,Year
0,Midmarket,France,Carretera,None,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0,6,June,2014
1,Government,France,Montana,None,1899.0,5,20,37980.0,0.0,37980.0,18990.0,18990.0,6,June,2014
2,Midmarket,France,Paseo,None,549.0,10,15,8235.0,0.0,8235.0,5490.0,2745.0,9,September,2013
3,Enterprise,France,Velo,None,1804.0,120,125,225500.0,0.0,225500.0,216480.0,9020.0,2,February,2014
4,Midmarket,France,VTT,None,2178.0,250,15,32670.0,0.0,32670.0,21780.0,10890.0,6,June,2014

## BONUS TIP: Merge all dataframes

In [9]:
from pathlib import Path
import pandas as pd

# Define filepath
current_dir = Path(__file__).parent if "__file__" in locals() else Path.cwd()
excel_filepath = current_dir / "data.xlsx"

# Load the Excel file
xl_file = pd.ExcelFile(excel_filepath)

# Create dicts for the arguments
usecols = {
    "India": "B:P",
}

skiprows = {
    "India": 1
}

# Use additional arguments to read the sheets
df_dict_flex = {}
for sheet_name in xl_file.sheet_names:
    df_dict_flex[sheet_name] = xl_file.parse(sheet_name, 
                                             usecols=usecols.get(sheet_name, None),
                                             skiprows=skiprows.get(sheet_name, None),
                                            )
df_dict_flex

{'Germany':               Segment  Country    Product Discount Band  Units Sold  \
 0          Government  Germany  Carretera          None      1321.0
 1           Midmarket  Germany  Carretera          None       888.0
 2          Government  Germany  Carretera          None      1513.0
 3           Midmarket  Germany    Montana          None       921.0
 4    Channel Partners  Germany    Montana          None      1545.0
 ..                ...      ...        ...           ...         ...
 135        Enterprise  Germany      Paseo          High      1085.0
 136         Midmarket  Germany      Paseo          High      1175.0
 137         Midmarket  Germany        VTT          High       492.0
 138         Midmarket  Germany        VTT          High      1175.0
 139        Enterprise  Germany        VTT          High       552.0

      Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  \
 0                      3          20      26420.0       0.00   26420.00
 1                      3          15      13320.0       0.00   13320.00
 2                      3         350     529550.0       0.00  529550.00
 3                      5          15      13815.0       0.00   13815.00
 4                      5          12      18540.0       0.00   18540.00
 ..                   ...         ...          ...        ...        ...
 135                   10         125     135625.0   20343.75  115281.25
 136                   10          15      17625.0    2643.75   14981.25
 137                  250          15       7380.0    1107.00    6273.00
 138                  250          15      17625.0    2643.75   14981.25
 139                  250         125      69000.0   10350.00   58650.00

        COGS     Profit  Month Number Month Name  Year
 0     13210   13210.00             1    January  2014
 1      8880    4440.00             6       June  2014
 2    393380  136170.00            12   December  2014
 3      9210    4605.00             3      March  2014
 4      4635   13905.00             6       June  2014
 ..      ...        ...           ...        ...   ...
 135  130200  -14918.75            10    October  2014
 136   11750    3231.25            10    October  2014
 137    4920    1353.00             7       July  2014
 138   11750    3231.25            10    October  2014
 139   66240   -7590.00            11   November  2014

 [140 rows x 15 columns],
 'Canada':               Segment Country    Product Discount Band  Units Sold  \
 0          Government  Canada  Carretera          None      1618.5
 1    Channel Partners  Canada    Montana          None      2518.0
 2          Enterprise  Canada    Montana          None      2665.5
 3          Enterprise  Canada    Montana          None       345.0
 4          Government  Canada      Paseo          None       292.0
 ..                ...     ...        ...           ...         ...
 135         Midmarket  Canada      Paseo          High      1614.0
 136         Midmarket  Canada      Paseo          High      2559.0
 137        Government  Canada        VTT          High       865.5
 138        Enterprise  Canada        VTT          High      2954.0
 139        Government  Canada      Paseo          High       723.0

      Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  \
 0                      3          20      32370.0       0.00   32370.00
 1                      5          12      30216.0       0.00   30216.00
 2                      5         125     333187.5       0.00  333187.50
 3                      5         125      43125.0       0.00   43125.00
 4                     10          20       5840.0       0.00    5840.00
 ..                   ...         ...          ...        ...        ...
 135                   10          15      24210.0    3631.50   20578.50
 136                   10          15      38385.0    5757.75   32627.25
 137                  250          20      17310.0    2596.50   14713.50
 138                  250         125     369250.0   55387.50  313862.50
 139                   10           7       5061.0     759.15    4301.85

          COGS    Profit  Month Number Month Name  Year
 0     16185.0  16185.00             1    January  2014
 1      7554.0  22662.00             6       June  2014
 2    319860.0  13327.50             7       July  2014
 3     41400.0   1725.00            10    October  2013
 4      2920.0   2920.00             2   February  2014
 ..        ...       ...           ...        ...   ...
 135   16140.0   4438.50             4      April  2014
 136   25590.0   7037.25             8     August  2014
 137    8655.0   6058.50             7       July  2014
 138  354480.0 -40617.50            11   November  2013
 139    3615.0    686.85             4      April  2014

 [140 rows x 15 columns],
 'United States Of America':               Segment                   Country   Product Discount Band  \
 0           Midmarket  United States Of America   Montana          None
 1          Government  United States Of America     Paseo          None
 2    Channel Partners  United States Of America     Paseo          None
 3          Enterprise  United States Of America      Velo          None
 4    Channel Partners  United States Of America  Amarilla          None
 ..                ...                       ...       ...           ...
 135    Small Business  United States Of America      Velo          High
 136        Enterprise  United States Of America      Velo          High
 137  Channel Partners  United States Of America      Velo          High
 138        Government  United States Of America       VTT          High
 139  Channel Partners  United States Of America       VTT          High

      Units Sold  Manufacturing Price  Sale Price  Gross Sales  Discounts  \
 0         615.0                    5          15       9225.0        0.0
 1        1143.0                   10           7       8001.0        0.0
 2         912.0                   10          12      10944.0        0.0
 3        2821.0                  120         125     352625.0        0.0
 4        1953.0                  260          12      23436.0        0.0
 ..          ...                  ...         ...          ...        ...
 135      2574.0                  120         300     772200.0   115830.0
 136      2438.0                  120         125     304750.0    45712.5
 137       914.0                  120          12      10968.0     1645.2
 138       267.0                  250          20       5340.0      801.0
 139      1806.0                  250          12      21672.0     3250.8

         Sales      COGS   Profit  Month Number Month Name  Year
 0      9225.0    6150.0   3075.0            12   December  2014
 1      8001.0    5715.0   2286.0            10    October  2014
 2     10944.0    2736.0   8208.0            11   November  2013
 3    352625.0  338520.0  14105.0             8     August  2014
 4     23436.0    5859.0  17577.0             4      April  2014
 ..        ...       ...      ...           ...        ...   ...
 135  656370.0  643500.0  12870.0            11   November  2013
 136  259037.5  292560.0 -33522.5            12   December  2013
 137    9322.8    2742.0   6580.8            12   December  2014
 138    4539.0    2670.0   1869.0            10    October  2013
 139   18421.2    5418.0  13003.2             5        May  2014

 [140 rows x 15 columns],
 'Mexico':               Segment Country    Product Discount Band  Units Sold  \
 0           Midmarket  Mexico  Carretera          None        2470
 1           Midmarket  Mexico    Montana          None        2470
 2      Small Business  Mexico    Montana          None         958
 3           Midmarket  Mexico      Paseo          None         974
 4          Government  Mexico      Paseo          None         883
 ..                ...     ...        ...           ...         ...
 135        Government  Mexico      Paseo          High        2851
 136        Government  Mexico      Paseo          High        2151
 137  Channel Partners  Mexico       Velo          High         500
 138    Small Business  Mexico   Amarilla          High         546
 139        Government  Mexico    Montana          High        1368

      Manufacturing Price  Sale Price  Gross Sales  Discounts     Sales  \
 0                      3          15        37050        0.0   37050.0
 1                      5          15        37050        0.0   37050.0
 2                      5         300       287400        0.0  287400.0
 3                     10          15        14610        0.0   14610.0
 4                     10           7         6181        0.0    6181.0
 ..                   ...         ...          ...        ...       ...
 135                   10         350       997850   149677.5  848172.5
 136                   10         350       752850   112927.5  639922.5
 137                  120          12         6000      900.0    5100.0
 138                  260         300       163800    24570.0  139230.0
 139                    5           7         9576     1436.4    8139.6

        COGS    Profit  Month Number Month Name  Year
 0     24700   12350.0             6       June  2014
 1     24700   12350.0             6       June  2014
 2    239500   47900.0             8     August  2014
 3      9740    4870.0             2   February  2014
 4      4415    1766.0             8     August  2014
 ..      ...       ...           ...        ...   ...
 135  741260  106912.5             5        May  2014
 136  559260   80662.5            11   November  2013
 137    1500    3600.0             3      March  2014
 138  136500    2730.0            10    October  2014
 139    6840    1299.6             2   February  2014

 [140 rows x 15 columns],
 'France':             Segment Country    Product Discount Band  Units Sold  \
 0         Midmarket  France  Carretera          None      2178.0
 1        Government  France    Montana          None      1899.0
 2         Midmarket  France      Paseo          None       549.0
 3        Enterprise  France       Velo          None      1804.0
 4         Midmarket  France        VTT          None      2178.0
 ..              ...     ...        ...           ...         ...
 135      Government  France      Paseo          High       293.0
 136       Midmarket  France       Velo          High      2826.0
 137      Enterprise  France       Velo          High       663.0
 138      Government  France        VTT          High       293.0
 139  Small Business  France   Amarilla          High      2475.0

      Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  \
 0                      3          15      32670.0       0.00   32670.00
 1                      5          20      37980.0       0.00   37980.00
 2                     10          15       8235.0       0.00    8235.00
 3                    120         125     225500.0       0.00  225500.00
 4                    250          15      32670.0       0.00   32670.00
 ..                   ...         ...          ...        ...        ...
 135                   10          20       5860.0     879.00    4981.00
 136                  120          15      42390.0    6358.50   36031.50
 137                  120         125      82875.0   12431.25   70443.75
 138                  250          20       5860.0     879.00    4981.00
 139                  260         300     742500.0  111375.00  631125.00

          COGS    Profit  Month Number Month Name  Year
 0     21780.0  10890.00             6       June  2014
 1     18990.0  18990.00             6       June  2014
 2      5490.0   2745.00             9  September  2013
 3    216480.0   9020.00             2   February  2014
 4     21780.0  10890.00             6       June  2014
 ..        ...       ...           ...        ...   ...
 135    2930.0   2051.00            12   December  2014
 136   28260.0   7771.50             5        May  2014
 137   79560.0  -9116.25             9  September  2014
 138    2930.0   2051.00            12   December  2014
 139  618750.0  12375.00             3      March  2014

 [140 rows x 15 columns],
 'India':             Segment Country    Product Discount Band  Units Sold  \
 0         Midmarket  France  Carretera          None      2178.0
 1        Government  France    Montana          None      1899.0
 2         Midmarket  France      Paseo          None       549.0
 3        Enterprise  France       Velo          None      1804.0
 4         Midmarket  France        VTT          None      2178.0
 ..              ...     ...        ...           ...         ...
 135      Government  France      Paseo          High       293.0
 136       Midmarket  France       Velo          High      2826.0
 137      Enterprise  France       Velo          High       663.0
 138      Government  France        VTT          High       293.0
 139  Small Business  France   Amarilla          High      2475.0

      Manufacturing Price  Sale Price  Gross Sales  Discounts      Sales  \
 0                      3          15      32670.0       0.00   32670.00
 1                      5          20      37980.0       0.00   37980.00
 2                     10          15       8235.0       0.00    8235.00
 3                    120         125     225500.0       0.00  225500.00
 4                    250          15      32670.0       0.00   32670.00
 ..                   ...         ...          ...        ...        ...
 135                   10          20       5860.0     879.00    4981.00
 136                  120          15      42390.0    6358.50   36031.50
 137                  120         125      82875.0   12431.25   70443.75
 138                  250          20       5860.0     879.00    4981.00
 139                  260         300     742500.0  111375.00  631125.00

          COGS    Profit  Month Number Month Name  Year
 0     21780.0  10890.00             6       June  2014
 1     18990.0  18990.00             6       June  2014
 2      5490.0   2745.00             9  September  2013
 3    216480.0   9020.00             2   February  2014
 4     21780.0  10890.00             6       June  2014
 ..        ...       ...           ...        ...   ...
 135    2930.0   2051.00            12   December  2014
 136   28260.0   7771.50             5        May  2014
 137   79560.0  -9116.25             9  September  2014
 138    2930.0   2051.00            12   December  2014
 139  618750.0  12375.00             3      March  2014

 [140 rows x 15 columns]}

In [10]:
df_merged = pd.concat(df_dict_flex.values(), ignore_index=True)
df_merged

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Month Name,Year
0,Government,Germany,Carretera,None,1321.0,3,20,26420.0,0.00,26420.00,13210.0,13210.00,1,January,2014
1,Midmarket,Germany,Carretera,None,888.0,3,15,13320.0,0.00,13320.00,8880.0,4440.00,6,June,2014
2,Government,Germany,Carretera,None,1513.0,3,350,529550.0,0.00,529550.00,393380.0,136170.00,12,December,2014
3,Midmarket,Germany,Montana,None,921.0,5,15,13815.0,0.00,13815.00,9210.0,4605.00,3,March,2014
4,Channel Partners,Germany,Montana,None,1545.0,5,12,18540.0,0.00,18540.00,4635.0,13905.00,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,Government,France,Paseo,High,293.0,10,20,5860.0,879.00,4981.00,2930.0,2051.00,12,December,2014
836,Midmarket,France,Velo,High,2826.0,120,15,42390.0,6358.50,36031.50,28260.0,7771.50,5,May,2014
837,Enterprise,France,Velo,High,663.0,120,125,82875.0,12431.25,70443.75,79560.0,-9116.25,9,September,2014
838,Government,France,VTT,High,293.0,250,20,5860.0,879.00,4981.00,2930.0,2051.00,12,December,2014
839,Small Business,France,Amarilla,High,2475.0,260,300,742500.0,111375.00,631125.00,618750.0,12375.00,3,March,2014

In [11]:
df_merged["Country"].unique()

array(['Germany', 'Canada', 'United States Of America', 'Mexico',
       'France'], dtype=object)